_target_: src.models.misr.MISR

data_dir: ${data_dir}/api_mashup # data_dir is specified in config.yaml
mashup_embed_path: embeddings/word_glove_mashup_embeddings.npy
api_embed_path: embeddings/partial/word_glove_api_embeddings.npy
conv_in_channels: 300
conv_out_channels: 100
out_channels: 128
text_len: 72
lr: 0.0001
weight_decay: 0.00001